### ISSUE TITLE
Demo page was hacked

### ISSUE THREAD

**Issue by MichaelApproved** [immense/quill-drag-and-drop-module#4]
The demo page was hacked and returns an SVG that's asking people to send Ethereum.

![Screenshot_061920_044304_PM](https://user-images.githubusercontent.com/222099/85178216-f28f7280-b24b-11ea-9132-39546c05c6c5.jpg)
![Screenshot_061920_044342_PM](https://user-images.githubusercontent.com/222099/85178254-0935c980-b24c-11ea-995b-5716a51014d3.jpg)

**Comment by cmbankester** [comment]
Wow, thanks for the heads up! Fixed
